<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Supplier Weekly Inventory Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }

        h2 {
            text-align: center;
            margin-bottom: 10px;
        }

        .report-meta {
            margin-bottom: 20px;
            text-align: center;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th, td {
            border: 1px solid #444;
            padding: 6px 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #fafafa;
        }

        .no-data {
            text-align: center;
            padding: 10px;
            font-style: italic;
        }
    </style>
</head>
<body>

    <h2>Supplier Weekly Inventory Report</h2>

    <div class="report-meta">
        <p><strong>Reporting Period:</strong> {{ $startOfWeek }} to {{ $endOfWeek }}</p>
        <p><strong>Generated By:</strong> {{ $roleName }}</p>
        <p><strong>Date Generated:</strong> {{ \Carbon\Carbon::now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>SKU</th>
                <th>Description</th>
                <th>Stock</th>
                <th>Reorder Level</th>
                <th>Unit of Measure</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($products as $product)
                <tr>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->sku }}</td>
                    <td>{{ $product->description ?? 'N/A' }}</td>
                    <td>{{ $product->stock }}</td>
                    <td>{{ $product->reorder_level }}</td>
                    <td>{{ $product->unit_of_measure }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" class="no-data">No inventory updates for this week.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

</body>
</html>
