<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Finance Inventory Report</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #333;
        }

        h2 {
            text-align: center;
            margin-bottom: 10px;
        }

        .report-meta {
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 10px;
        }

        th, td {
            border: 1px solid #555;
            padding: 6px 10px;
            text-align: left;
        }

        th {
            background-color: #f0f0f0;
        }

        tfoot td {
            font-weight: bold;
            background-color: #f9f9f9;
        }

        .center {
            text-align: center;
        }
    </style>
</head>
<body>

    <h2>Finance Inventory Report</h2>

    <div class="report-meta">
        <p><strong>Reporting Period:</strong> {{ $startOfWeek ?? 'N/A' }} to {{ $endOfWeek ?? 'N/A' }}</p>
        <p><strong>Generated By:</strong> {{ $roleName }}</p>
        <p><strong>Date Generated:</strong> {{ \Carbon\Carbon::now()->format('Y-m-d H:i:s') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>SKU</th>
                <th>Unit Price</th>
                <th>Stock</th>
                <th>Total Value</th>
                <th>Vendor</th>
            </tr>
        </thead>
        <tbody>
            @php $grandTotal = 0; @endphp
            @foreach ($products as $product)
                @php
                    $totalValue = $product->stock * $product->unit_price;
                    $grandTotal += $totalValue;
                @endphp
                <tr>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->sku }}</td>
                    <td>{{ number_format($product->unit_price, 2) }}</td>
                    <td>{{ $product->stock }}</td>
                    <td>{{ number_format($totalValue, 2) }}</td>
                    <td>{{ $product->vendor->name ?? 'N/A' }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="center">Grand Total</td>
                <td colspan="2">{{ number_format($grandTotal, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    


</body>
</html>
